GET http://localhost:4004/service/EMLATrackerService/EMLACustomers
Authorization: Basic user:passwd


###
POST http://localhost:4004/service/EMLATrackerService/EMLACustomers
Authorization: Basic user:passwd
Content-Type: application/json

{
    "externalID": "315",
    "customerName": "John Doe",
    "customerNumber": "CUST001",
    "emlaType": "Private Cloud ERP",
    "region": "North America",
    "country": "USA",
    "startDate": "2023-10-01",
    "btpOnbAdvNome": "Adv Nome",
    "btpOnbAdvEmail": "advnome@example.com",
    "status": "Active"
}

###
POST http://localhost:4004/service/EMLATrackerService/EMLACustomers
Authorization: Basic user:passwd
Content-Type: application/json

{
  "ID": "1bb3e68b-0189-487d-aeaf-afdc2d231c8d",
  "externalID": "315",
  "customerName": "John Doe",
  "customerNumber": "CUST001",
  "emlaType": "Public Cloud ERP 2",
  "region": "North America",
  "country": "USA",
  "startDate": "2023-10-01",
  "btpOnbAdvNome": "Adv Nome",
  "btpOnbAdvEmail": "advnome@example.com",
  "status": "Active",
  "trackApp": null
}


###
POST http://localhost:4004/service/EMLATrackerService/onbTrackApp
Authorization: Basic user:passwd
Content-Type: application/json

{
  "ID": "1bb3e68b-0189-487d-aeaf-afdc2d231c8d"
}

