GET http://localhost:4004/service/EMLATrackerService/EMLACustomers
Authorization: Basic user:passwd


###
POST http://localhost:4004/service/EMLATrackerService/EMLACustomers
Authorization: Basic user:passwd
Content-Type: application/json

{
    "externalID": "315",
    "customerName": "John Doe",
    "customerNumber": "CUST001",
    "emlaType": "Private Cloud ERP",
    "region": "North America",
    "country": "USA",
    "startDate": "2023-10-01",
    "btpOnbAdvNome": "Adv Nome",
    "btpOnbAdvEmail": "advnome@example.com",
    "status": "Active"
}

###
POST http://localhost:4004/service/EMLATrackerService/EMLACustomers
Authorization: Basic user:passwd
Content-Type: application/json

{
  "ID": "1bb3e68b-0189-487d-aeaf-afdc2d231c8d",
  "externalID": "315",
  "customerName": "John Doe",
  "customerNumber": "CUST001",
  "emlaType": "Public Cloud ERP 2",
  "region": "North America",
  "country": "USA",
  "startDate": "2023-10-01",
  "btpOnbAdvNome": "Adv Nome",
  "btpOnbAdvEmail": "advnome@example.com",
  "status": "Active",
  "trackApp": null
}


###
POST http://localhost:4004/service/EMLATrackerService/onbTrackApp
Authorization: Basic user:passwd
Content-Type: application/json

{
  "ID": "1bb3e68b-0189-487d-aeaf-afdc2d231c8d"
}

###
PATCH http://localhost:60431/service/EMLATrackerService/EMLACustomers('00908c20-3460-4629-9b4d-256ed276427e')
Authorization: Basic user:passwd
Content-Type: application/json

{
  "trackApp": "MANUAL-TP1-ABC123",
  "trackAppTP2": "MANUAL-TP1-ABC123",
  "trackAppSH": "MANUAL-TP1-ABC123",
  "isTrackAppCompleted"   : true,
   "isTrackAppTP2Completed" : false ,
   "isTrackAppSHCompleted"  : true
}

###
PATCH http://localhost:4004/service/EMLATrackerService/EMLACustomers('10195ed5-db9b-4e2d-913d-be37b8689c3f')
Authorization: Basic user:passwd
Content-Type: application/json
If-Match: *

{
  "trackAppTP2": "MANUAL-TP2-DEF456"
}

###
POST http://localhost:4004/service/EMLATrackerService/EMLACustomers
Authorization: Basic user:passwd
Content-Type: application/json

    {
      "createdAt": "2025-11-03T21:05:23.963Z",
      "createdBy": "privileged",
      "modifiedAt": "2025-11-03T21:06:08.558Z",
      "modifiedBy": "privileged",
      "ID": "013e35ce-308b-402e-a5a0-a1be7541d154",
      "externalID": "261",
      "customerName": "IONOS SE",
      "customerNumber": "1105676",
      "emlaType": "Integration Suite",
      "region": "CS MEE",
      "country": "Germany",
      "startDate": "2025-09-15",
      "erpOnbAdvNome": "",
      "btpOnbAdvNome": "Julia Baust",
      "btpOnbAdvEmail": "eduardo.fagundes@sap.com",
      "status": "Open",
      "trackApp": "3c29a778-1a47-465b-91fa-2f640c9a1386",
      "trackAppSH": "359d2bed-8393-4689-8c4b-03b6ed7ece6a",
      "trackAppTP2": "",
      "isTrackAppCompleted": false,
      "isTrackAppTP2Completed": false,
      "isTrackAppSHCompleted": false,
      "completedOn": null
    }

###
# Update session completion status by checking webservice
POST http://localhost:4004/service/EMLATrackerService/updateSessionStatus
Authorization: Basic user:passwd
Content-Type: application/json

{}

###