### Test syncEMLAData action locally
POST http://localhost:4004/service/EMLATrackerService/syncEMLAData
Content-Type: application/json

{}

### Test with metadata check
GET http://localhost:4004/service/EMLATrackerService/$metadata

### Check if service is running
GET http://localhost:4004/service/EMLATrackerService/

### 
POST http://localhost:4004/service/EMLATrackerService/syncEMLAData
Content-Type: application/json

{}


####
POST http://localhost:4004/service/EMLATrackerService/syncEMLAData
Content-Type: application/json

{}