/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const onbtrackapp_Logic = require('./code/onbtrackapp-logic');
const emlacustomers_Logic = require('./code/emlacustomers-logic');
const csvUpload_Logic = require('./code/csv-upload-logic');
const syncEmla_Logic = require('./code/sync-emla-logic');

class EMLATrackerService extends LCAPApplicationService {
    async init() {

        this.on('onbTrackApp', async (request) => {
            return onbtrackapp_Logic(request);
        });

        this.on('setCompleted', 'EMLACustomers', async (request) => {
            return emlacustomers_Logic(request);
        });

        this.on('uploadCSV', async (request) => {
            return csvUpload_Logic(request);
        });

        this.on('syncEMLAData', async (request) => {
            return syncEmla_Logic(request);
        });

        return super.init();
    }
}


module.exports = {
    EMLATrackerService
};